abc = "test";
abc = "testxxxx";
grezer erzre
ôkhmewklmhknewnkh
lhnwejhwenjkwe
klnwekjhnwenhjwejk
hwejhwejhnkwejhwejk
hnwjknhkewhwenk
mkhkmôhmôe wehewhew
iowehweioomlhkwe
lnknikoher
klnwjhnwejhwnel
hklbmwenhjwekjn
kehblwekhewkn
hôlmwekhnwlnhkwe
e,nmkhmwklhklew
khmbewlkhwnhjwe
gekwjhnwjekjnhwejk
lghnwejnhknwew
hkmnwejhnweklhnwje
hbeklwnhjwejhnwe
mlewkhnwelkhew
lenwjknhjwekwje
ohewkhlwenkk
knmkrwemhnwlknhe
gwegwegeôm
afgrehtjz gewgew
goičwihwehew
gwegwepomweôlb
klnwkheklwnhlkwe
hwiojhlewk
lihwkkhwklmeh
poôweôhew
hwehew wrbehre
rweberh hretnjtr
gwôlmhew; wbreh
grehehremnmejjre
gezwgzrwgzz
yeyggewlngw
gwekhnwlehwe
hjvhgkwelkwenhwe
hkbizibierye ureure

gweher
hrhre
gewhre
uerure
gewzaeru
tritritr
